# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:

    docker:
      - image: circleci/android:api-29

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Creating file local
          command: |
            echo api_public_key=\"025f2cd3ea0aaa7b9c445d8a5897de59\"  >> /home/circleci/repo/local.properties
            echo api_private_key=\"45f27290cbe76b21e99247f8414e8204bb950230\" >> /home/circleci/repo/local.properties
            cat local.properties

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Check code style
          command: ./gradlew clean spotlessCheck --no-daemon

      - run:
          name: Generate all unit test reports
          command: ./gradlew clean jacocoTestReport --no-daemon

      - run:
          name: Upload reports to Codecov
          command: bash <(curl -s https://codecov.io/bash -v) -f app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

      - run:
          name: Run Tests
          command: ./gradlew lint test

      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports

      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results

